baseURL: https://sbhwang.vercel.app
copyright: "© {year} Su Bhin Hwang"

defaultContentLanguage: en
defaultContentLanguageInSubdir: false

enableRobotsTXT: true
summaryLength: 30

markup:
  goldmark:
    renderer:
      unsafe: true

module:
  imports:
    - path: github.com/HugoBlox/hugo-blox-builder/modules/blox-tailwind

security:
  funcs:
    getenv:
      - ^HUGO_
      - ^WC_
