ko:
  locale: ko-KR
  label: 한국어
  weight: 2
  title: "황수빈"
  contentDir: content/ko
  params:
    subtitle: "서울대학교 수학교육과 박사 수료 / 반포고등학교 교사"
  menus:
    main:
      - name: "홈"
        url: "/ko/"
        weight: 10
      - name: "논문"
        url: "/ko/publication/"
        weight: 20
      - name: "활동"
        url: "/ko/activities/"
        weight: 30

en:
  locale: en-US
  label: English
  weight: 1
  title: "Su Bhin Hwang"
  contentDir: content/en
  params:
    subtitle: "Ph.D. Candidate at SNU / Math Teacher at Banpo High School"
  menus:
    main:
      - name: "Home"
        url: "/"
        weight: 10
      - name: "Publications"
        url: "/publication/"
        weight: 20
      - name: "Activities"
        url: "/activities/"
        weight: 30
